# -*- coding: utf-8 -*-
"""mistral_definitivo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aiUGk6r1YbR43BBhAtWOliz1W51lzUs5
"""

# ================================================================
# PIPELINE FINAL– DSS HÍBRIDO ROBUSTO
# ================================================================

from google.colab import userdata
MISTRAL_API_KEY = userdata.get('MISTRAL_API_KEY')

import requests, json, logging, time, re, zipfile, os, joblib
import pandas as pd
import numpy as np
from typing import Optional, Dict, Any
from jsonschema import validate, ValidationError

# ----------------------------------------------------------------
# CONFIGURACIÓN
# ----------------------------------------------------------------
MISTRAL_URL = "https://api.mistral.ai/v1/chat/completions"
MISTRAL_MODEL = "mistral-small-latest"
HEADERS = {"Authorization": f"Bearer {MISTRAL_API_KEY}", "Content-Type": "application/json"}
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

FEATURE_SCHEMA = {
    "type": "object",
    "properties": {
        "zona_lesion": {"type": "string"},
        "severidad_lesion": {"type": "number"},
        "tendencia_lesion": {"type": "string"},
        "fatiga_cualitativa": {"type": "number"},
        "calidad_suenio_cualitativa": {"type": "number"},
        "estres_cualitativo": {"type": "number"},
        "dolor_muscular_cualitativo": {"type": "number"},
        "confianza_extraccion": {"type": "number"}
    },
    "required": ["severidad_lesion"]
}

DECISION_SCHEMA = {
    "type": "object",
    "properties": {
        "decision": {"type": "string"},
        "risk_score": {"type": "number"},
        "razonamiento": {"type": "string"}
    },
    "required": ["decision", "risk_score"]
}

# ----------------------------------------------------------------
# LLAMADA HTTP ROBUSTA
# ----------------------------------------------------------------
def llamar_modelo(prompt: str, max_tokens=300, temperature=0.2, retries=2) -> Optional[Dict]:
    payload = {"model": MISTRAL_MODEL, "messages": [{"role": "user", "content": prompt}],
               "max_tokens": max_tokens, "temperature": temperature}
    for intento in range(retries + 1):
        try:
            start = time.time()
            resp = requests.post(MISTRAL_URL, headers=HEADERS, json=payload, timeout=30)
            latency = time.time() - start
            if resp.status_code == 429:
                logging.warning(f"Rate limit (intento {intento+1}). Esperando 5s...")
                time.sleep(5); continue
            resp.raise_for_status()
            content = resp.json()["choices"][0]["message"]["content"]
            logging.info(f"Latencia Mistral: {latency:.2f}s")
            return {"text": content, "latency": latency}
        except requests.exceptions.RequestException as e:
            logging.error(f"Error HTTP (intento {intento+1}): {e}")
            if intento < retries: time.sleep(3)
        except Exception as e:
            logging.error(f"Error inesperado: {e}"); break
    return None

# ----------------------------------------------------------------
# EXTRACCIÓN DE JSON ROBUSTA + REPARACIÓN
# ----------------------------------------------------------------
def extraer_json_seguro(texto: str) -> Optional[Dict]:
    try:
        match = re.search(r'\{.*\}', texto, re.DOTALL)
        if match: return json.loads(match.group().replace("\n", " ").strip())
    except: pass
    try:
        start, end = texto.find("{"), texto.rfind("}") + 1
        if start != -1 and end > start: return json.loads(texto[start:end])
    except: pass
    return None

def call_llm_json(prompt: str, schema: Dict, retries: int = 2) -> Optional[Dict]:
    for _ in range(retries + 1):
        raw = llamar_modelo(prompt)
        if not raw: continue
        parsed = extraer_json_seguro(raw["text"])
        if parsed:
            try:
                validate(instance=parsed, schema=schema); return parsed
            except ValidationError: pass
        fix_prompt = f"""Corrige este JSON para que cumpla EXACTAMENTE este schema:
{json.dumps(schema, indent=2)}
JSON a corregir:
{raw['text']}
Devuelve SOLO JSON válido."""
        raw_fix = llamar_modelo(fix_prompt)
        if raw_fix:
            parsed = extraer_json_seguro(raw_fix["text"])
            if parsed:
                try:
                    validate(instance=parsed, schema=schema); return parsed
                except: continue
    return None

# ----------------------------------------------------------------
# VALIDACIÓN DE RANGOS
# ----------------------------------------------------------------
def validar_features(f: Dict) -> Dict:
    def clamp(v, a, b, d):
        try: return max(a, min(b, float(v)))
        except: return d
    return {
        "zona_lesion": str(f.get("zona_lesion", "desconocida")),
        "severidad_lesion": clamp(f.get("severidad_lesion"), 1, 10, 5),
        "tendencia_lesion": str(f.get("tendencia_lesion", "estable")),
        "fatiga_cualitativa": clamp(f.get("fatiga_cualitativa"), 1, 10, 5),
        "calidad_suenio_cualitativa": clamp(f.get("calidad_suenio_cualitativa"), 1, 10, 5),
        "estres_cualitativo": clamp(f.get("estres_cualitativo"), 1, 10, 5),
        "dolor_muscular_cualitativo": clamp(f.get("dolor_muscular_cualitativo"), 1, 10, 5),
        "confianza_extraccion": clamp(f.get("confianza_extraccion"), 0, 1, 0.5)
    }

def validar_decision(d: Dict) -> Optional[Dict]:
    try:
        if d.get("decision") not in ["ROJO", "ÁMBAR", "VERDE"]: return None
        risk = float(d.get("risk_score", 0))
        if not (0 <= risk <= 1): return None
        return {"decision": d["decision"], "risk_score": round(risk, 2), "razonamiento": str(d.get("razonamiento", ""))}
    except: return None

# ----------------------------------------------------------------
# PARSER HEURÍSTICO COMPLETO (MEJORADO: confianza 0.3)
# ----------------------------------------------------------------
class HeuristicParser:
    def parse(self, text):
        t = text.lower()
        zonas = ["tobillo izquierdo","tobillo derecho","rodilla izquierda","rodilla derecha",
                 "cadera","espalda baja","isquiotibiales","cuádriceps","ingle"]
        zona = "desconocida"
        for z in zonas:
            if z in t: zona = z.replace(" ","_"); break
        severidad = 8 if any(w in t for w in ["severo","agudo","inflamación","muy dolor"]) else \
                    6 if any(w in t for w in ["dolor","molestia","preocupante"]) else \
                    4 if any(w in t for w in ["ligera","leve","tensión"]) else 2
        tendencia = "mejorando" if any(w in t for w in ["mejorando","recuperando","mejor"]) else \
                    "empeorando" if any(w in t for w in ["empeorando","peor","crítico"]) else "estable"
        fatigue = 9 if any(w in t for w in ["fatiga máxima","muy cansado","exhausto"]) else \
                  5 if any(w in t for w in ["fatiga moderada","algo cansado","cansado"]) else \
                  3 if any(w in t for w in ["fatiga normal","fatiga baja","descansado"]) else 5
        sleep = 2 if any(w in t for w in ["sin dormir","dormir mal","muy mal","pobre"]) else \
                5 if any(w in t for w in ["regular","dormir regular"]) else \
                8 if any(w in t for w in ["bien","duerme bien","excelente","muy bien"]) else 5
        stress = 8 if any(w in t for w in ["estrés alto","muy estresado","preocupado"]) else \
                 5 if any(w in t for w in ["estrés moderado","algo estresado"]) else \
                 2 if any(w in t for w in ["estrés bajo","relajado"]) else 5
        soreness = 8 if any(w in t for w in ["dolor muscular generalizado","muy dolorido"]) else \
                   5 if any(w in t for w in ["dolor muscular","molestia"]) else \
                   2 if any(w in t for w in ["sin dolor","dolor mínimo"]) else 3
        return {"zona_lesion":zona,"severidad_lesion":severidad,"tendencia_lesion":tendencia,
                "fatiga_cualitativa":fatigue,"calidad_suenio_cualitativa":sleep,
                "estres_cualitativo":stress,"dolor_muscular_cualitativo":soreness,
                "confianza_extraccion":0.3}   #  MEJORA: confianza realista para el heurístico

# ----------------------------------------------------------------
# PARSING NUMÉRICO PREVIO (MEJORA: extraer números del reporte)
# ----------------------------------------------------------------
def parsear_numeros_del_reporte(reporte: str) -> Dict:
    nums = {}
    for campo, patron in [("fatiga", r'Fatiga:\s*(\d+)/10'),
                           ("sueno", r'Sueño:\s*(\d+)/10'),
                           ("estres", r'Estrés:\s*(\d+)/10'),
                           ("dolor", r'Dolor:\s*(\d+)/10'),
                           ("acwr", r'ACWR:\s*([\d.]+)')]:
        m = re.search(patron, reporte)
        if m: nums[campo] = float(m.group(1))
    return nums

# ----------------------------------------------------------------
# EXTRACCIÓN CUALITATIVA (MEJORADA: prompt con números ya parseados)
# ----------------------------------------------------------------
def extraer_caracteristicas_cualitativas(reporte: str, use_llm: bool = True) -> Dict:
    if use_llm:
        numeros = parsear_numeros_del_reporte(reporte)
        prompt = f"""Eres un asistente médico-deportivo. Extrae del siguiente reporte los campos en formato JSON.
Responde SOLO con el JSON, sin explicaciones adicionales.

USA EXACTAMENTE estos valores numéricos (no los interpretes ni los cambies):
{json.dumps(numeros, ensure_ascii=False)}

Formato:
{{
  "zona_lesion": "nombre de la zona en español",
  "severidad_lesion": número del 1 al 10,
  "tendencia_lesion": "mejorando" | "estable" | "empeorando",
  "fatiga_cualitativa": número del 1 al 10,
  "calidad_suenio_cualitativa": número del 1 al 10,
  "estres_cualitativo": número del 1 al 10,
  "dolor_muscular_cualitativo": número del 1 al 10,
  "confianza_extraccion": número del 0 al 1
}}

Reporte: "{reporte}" """
        parsed = call_llm_json(prompt, FEATURE_SCHEMA)
        if parsed:
            features = validar_features(parsed)
            if features["confianza_extraccion"] < 0.4:
                logging.warning("Confianza de extracción baja (<0.4). Derivando a heurístico.")
                return HeuristicParser().parse(reporte)
            logging.info("Extracción realizada con Mistral")
            return features
        logging.warning("Mistral no disponible o respuesta inválida. Usando parser heurístico.")
    return HeuristicParser().parse(reporte)

# ----------------------------------------------------------------
# DECISIÓN HÍBRIDA (SE MANTIENE IGUAL QUE EN v3 – COMPLETA)
# ----------------------------------------------------------------
def decision_arbitrada(ml_prob: float, features: Dict, reporte: str,
                       acwr_real: float = 0.0, use_llm: bool = True) -> Dict:
    if features.get("confianza_extraccion", 1.0) < 0.4:
        use_llm = False
        logging.info("Decisión forzada a heurístico por baja confianza en extracción.")

    if ml_prob > 0.7 or acwr_real > 1.5:
        decision, risk_score = "ROJO", min(1.0, ml_prob + 0.15)
        if ml_prob > 0.7 and acwr_real > 1.5:
            razon = f"Regla clínica: alta probabilidad de lesión ({ml_prob:.2f}) y ACWR elevado ({acwr_real:.2f}). REPOSO OBLIGATORIO."
        elif ml_prob > 0.7:
            razon = f"Regla clínica: alta probabilidad de lesión ({ml_prob:.2f}). REPOSO OBLIGATORIO."
        else:
            razon = f"Regla clínica: ACWR muy elevado ({acwr_real:.2f}). REPOSO OBLIGATORIO."
        logging.info(json.dumps({"fuente":"REGLA","decision":decision,"risk":risk_score}))
        return {"decision":decision,"risk_score":round(risk_score,2),"razonamiento":razon,"fuente":"REGLA"}

    if (ml_prob < 0.35 and
        features["fatiga_cualitativa"] < 6 and
        features["dolor_muscular_cualitativo"] < 5 and
        features["calidad_suenio_cualitativa"] > 4 and
        features["tendencia_lesion"] != "empeorando"):
        return {
            "decision": "VERDE",
            "risk_score": round(ml_prob, 2),
            "razonamiento": "Bajo riesgo global consistente. Sin signos de alarma.",
            "fuente": "REGLA_SUAVE"
        }

    if use_llm:
        numeros = parsear_numeros_del_reporte(reporte)
        prompt = f"""Eres un médico deportivo experto en prevención de lesiones.

DATOS PROPORCIONADOS (NO INVENTES VALORES ADICIONALES):
- Probabilidad de lesión según IA: {ml_prob}
- Características cualitativas extraídas: {json.dumps(features, ensure_ascii=False)}
- Valores numéricos conocidos: {json.dumps(numeros, ensure_ascii=False)}
- Reporte original: "{reporte}"

REGLAS DE APOYO (Gabbett 2016):
- Si fatiga > 7 → ÁMBAR.
- Si sueño < 4 → riesgo.
- Si dolor muscular > 6 → evitar VERDE.
- En ausencia de factores de riesgo, considera VERDE.

IMPORTANTE:
- NO inventes valores.
- Usa SOLO los datos proporcionados.

Devuelve SOLO JSON con tu decisión:
{{
  "decision": "ÁMBAR" | "VERDE",
  "risk_score": número entre 0 y 1,
  "razonamiento": "explica brevemente"
}}"""
        raw = call_llm_json(prompt, DECISION_SCHEMA)
        if raw:
            validado = validar_decision(raw)
            if validado:
                if features["fatiga_cualitativa"] > 8:
                    validado["decision"] = "ÁMBAR"; validado["razonamiento"] += " (Ajuste por fatiga extrema)"
                if features["dolor_muscular_cualitativo"] > 7:
                    validado["decision"] = "ÁMBAR"; validado["razonamiento"] += " (Ajuste por dolor severo)"
                if features["calidad_suenio_cualitativa"] < 3:
                    validado["decision"] = "ÁMBAR"; validado["razonamiento"] += " (Ajuste por sueño muy pobre)"
                logging.info(json.dumps({"fuente":"LLM","decision":validado["decision"],"risk":validado["risk_score"]}))
                validado["fuente"] = "LLM"
                return validado
        logging.warning("Mistral no disponible o decisión inválida. Aplicando fallback heurístico.")

    f, d, s = features["fatiga_cualitativa"]/10, features["dolor_muscular_cualitativo"]/10, 1-features["calidad_suenio_cualitativa"]/10
    risk = ml_prob*0.5 + f*0.15 + d*0.15 + s*0.1 + (f*d)*0.1
    if features["tendencia_lesion"] == "empeorando": risk += 0.15; razon = "Tendencia empeora. "
    elif features["tendencia_lesion"] == "mejorando": risk -= 0.10; razon = "Tendencia mejora. "
    else: razon = ""
    conf = features.get("confianza_extraccion", 1.0)
    if conf < 0.7: risk += (0.7 - conf) * 0.2
    risk = max(0.0, min(risk, 1.0))
    decision = "ÁMBAR" if risk > 0.4 else "VERDE"
    razon += "Riesgo combinado moderado." if decision == "ÁMBAR" else "Riesgo combinado bajo."
    logging.info(json.dumps({"fuente":"HEURISTICO","decision":decision,"risk":round(risk,2)}))
    return {
        "decision": decision,
        "risk_score": round(risk, 2),
        "razonamiento": razon,
        "fuente": "HEURISTICO",
        "debug": {
            "ml_prob": round(ml_prob, 3),
            "acwr": round(acwr_real, 2),
            "fatiga": features["fatiga_cualitativa"],
            "sueno": features["calidad_suenio_cualitativa"],
            "dolor": features["dolor_muscular_cualitativo"],
            "confianza": features["confianza_extraccion"]
        }
    }

import sys
!{sys.executable} -m pip install catboost

# ================================================================
# CARGA DE MODELOS Y DATASET (DESDE ZIP)
# ================================================================
ZIP_NAME = 'resultados_tfg.zip'
if not os.path.exists(ZIP_NAME):
    print("El archivo resultados_tfg.zip no se encuentra. Súbelo a Colab.")
else:
    with zipfile.ZipFile(ZIP_NAME, 'r') as z:
        for f in ['content/scaler.pkl','content/modelo_stacking_ensemble.pkl','content/dataset_sintetico_soccermon.csv']:
            if f in z.namelist():
                info = z.getinfo(f); info.filename = os.path.basename(f); z.extract(info); print(f"✓ {info.filename}")
    scaler = joblib.load('scaler.pkl')
    stack = joblib.load('modelo_stacking_ensemble.pkl')
    df = pd.read_csv('dataset_sintetico_soccermon.csv')

    feature_cols = ['distance_m','hsr_distance_m','acwr','ctl','atl',
                    'fatigue_score','sleep_quality','stress','muscle_soreness',
                    'inter_acwr_fatigue','th_acwr_fatigue','th_stress_sleep','inter_sleep_sore']

    ejemplos = df.sample(4, random_state=42)
    X_muestra = ejemplos[feature_cols].copy()
    X_scaled = scaler.transform(pd.DataFrame(X_muestra, columns=feature_cols))
    probas = stack.predict_proba(X_scaled)[:, 1]
    acwr_reales = X_muestra['acwr'].values

    def generar_reporte(fila):
        zona = "muslo" if fila['muscle_soreness']>5 else "sin zona definida"
        return (f"Zona: {zona}. Fatiga: {int(fila['fatigue_score'])}/10. "
                f"Sueño: {int(fila['sleep_quality'])}/10. Estrés: {int(fila['stress'])}/10. "
                f"Dolor: {int(fila['muscle_soreness'])}/10. ACWR: {fila['acwr']:.2f}")

    ejemplos['reporte'] = X_muestra.apply(generar_reporte, axis=1)
    casos = [{"reporte": ejemplos['reporte'].iloc[i], "ml_prob": float(probas[i])} for i in range(len(ejemplos))]

    print("="*80)
    print("DEMOSTRACIÓN FINAL – DSS HÍBRIDO CON TRAZABILIDAD (v3.1)")
    print("="*80)
    for i, caso in enumerate(casos, 1):
        print(f"\n--- Caso {i} ---")
        print(f"Reporte: {caso['reporte']}")
        print(f"P(lesión): {caso['ml_prob']:.3f}")
        features = extraer_caracteristicas_cualitativas(caso["reporte"], use_llm=True)
        decision = decision_arbitrada(caso["ml_prob"], features, caso["reporte"],
                                      acwr_real=acwr_reales[i-1], use_llm=True)
        print(f"Decisión: {decision['decision']} | Risk: {decision['risk_score']} | Fuente: {decision['fuente']}")
        print(f"Razonamiento: {decision['razonamiento']}")
        if "debug" in decision:
            print(f"Debug: {json.dumps(decision['debug'], ensure_ascii=False)}")

